checkpoint: /home/max/TTS/pycharm-sova/sova-tts-engine/output_dir/checkpoint_49000
hparams: /home/max/TTS/pycharm-sova/sova-tts-engine/data/hparams.yaml
use_gst: True
emotion_wav: /home/max/TTS/pycharm-sova/emotion_voices/happy.wav
output_folder: ./tts_output

# waveglow parameters

waveglow_path: /home/max/TTS/pycharm-sova/sova-tts-vocoder/checkpoints/waveglow_256channels_universal_v5.pt
sigma: 1.0
sampling_rate: 22050
denoiser_strength: 0.0
is_fp16: False
