# tacatron2 parameters

#tacotron_path: /home/max/TTS/pycharm-sova/sova-tts-engine/output_dir/checkpoint_49000
tacotron_path: /home/max/TTS/pycharm-sova/sova-tts-engine/output_dir/trained_with_gst2
#tacotron_path: /home/max/TTS/pycharm-sova/sova-tts-engine/output_dir/trained_without_gst
#tacotron_path: /home/max/TTS/pycharm-sova/sova-tts-engine/output_dir/tacotron2_statedict.pt
hparams: /home/max/TTS/pycharm-sova/sova-tts-engine/data/hparams.yaml
#hparams: /home/max/TTS/pycharm-sova/sova-tts-engine/data/hparams_without_gst.yaml
use_gst: True
emotion_wav: /home/max/TTS/pycharm-sova/emotion_voices/neutral.wav


# waveglow parameters

waveglow_path: /home/max/TTS/pycharm-sova/sova-tts-vocoder/checkpoints/waveglow_256channels_universal_v5.pt
sampling_rate: 22050

# Additional parameters 

explicit_filter: False # for non SSML text only
explicit_dictionary: /home/max/TTS/pycharm-sova/explicit_dictionary.txt
output_folder: ./tts_output
